name: jolt
description: A lightweight, high-performance reactive signals library for Dart/Flutter with fine-grained updates and intelligent resource management.
version: 1.0.3

repository: https://github.com/vowdemon/jolt
homepage: https://jolt.vowdemon.com

topics:
  - jolt
  - state-management
  - signals

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  meta: ^1.0.0
  shared_interfaces: ^0.0.2

dev_dependencies:
  lints: ^5.0.0
  test: any
