name: jolt_flutter_hooks
description: "Setup package for the Jolt reactive state management system, providing declarative hooks"

repository: https://github.com/vowdemon/jolt
homepage: https://jolt.vowdemon.com

topics:
  - jolt
  - state-management
  - signals
  - hook
  - setup

version: 1.0.0-beta.1

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  jolt_flutter: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
