name: jolt_hooks
description: "Flutter hooks integration for the Jolt reactive state management system, providing declarative hooks for signals, computed values, effects, and more."

repository: https://github.com/vowdemon/jolt
homepage: https://jolt.vowdemon.com

topics:
  - jolt
  - state-management
  - signals
  - hook

version: 1.0.3

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.21.3+1
  jolt: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  jolt_flutter: ^1.1.2

  flutter_lints: ^5.0.0
