name: jolt_flutter
description: "A Flutter extension of jolt that provides reactive UI support, enabling automatic synchronization between state and interface."
version: 0.0.7
repository: https://github.com/vowdemon/jolt

topics:
  - jolt
  - state-management
  - signals
  - flutter

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  jolt: ^0.0.7
  shared_interfaces: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

