name: jolt_flutter
description: "Flutter library for jolt reactive signals library that builds reactive widgets from signals, automatically updating UI when signals change."
version: 3.0.0

repository: https://github.com/vowdemon/jolt
homepage: https://jolt.vowdemon.com

topics:
  - jolt
  - state-management
  - signals
  - flutter

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  jolt: ^3.0.0
  meta: ^1.0.0
  shared_interfaces: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
