name: jolt_lint
description: Lint tool for the Jolt reactive state management ecosystem, providing code quality checks and developer assistance.

repository: https://github.com/vowdemon/jolt

resolution: workspace

version: 3.0.1

topics:
  - jolt
  - state-management
  - signals
  - lint

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  analysis_server_plugin: ^0.3.3
  analyzer: ">=8.4.0 <10.0.0"
  analyzer_plugin: ^0.13.10

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
