name: jolt_surge
description: A lightweight reactive state container for Flutter, built on Jolt Signals and inspired by BLoC's Cubit architecture.

repository: https://github.com/vowdemon/jolt
homepage: https://jolt.vowdemon.com

topics:
  - jolt
  - state-management
  - signals
  - surge

version: 3.1.0-dev.0

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  jolt_flutter: ^3.1.0-dev.0
  provider: ^6.1.5+1
  shared_interfaces: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
