name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "packages/**"

jobs:
  ci:
    name: Analyze and test Dart packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment and cache dependencies
        uses: ./.github/actions/prepare
      - name: Analyze packages
        run: melos run analyze
        shell: bash
      - name: Run packages tests
        run: melos run test
        shell: bash

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage/combined.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release-trigger:
    name: Trigger release workflow
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ needs.ci.result == 'success' && contains(github.event.head_commit.message, 'chore(release)') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trigger release workflow
        run: |
          gh workflow run publish-tag.yml \
          --ref main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
