name: test

on:
  pull_request:
    paths:
      - "packages/**"

jobs:
  ci:
    name: Analyze and test Dart packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment and cache dependencies
        uses: ./.github/actions/prepare
      - name: Analyze packages
        uses: invertase/github-action-dart-analyzer@v3
        with:
          fatal-infos: true
      - name: Run packages tests
        run: melos run test
        shell: bash
      - name: Combine coverage reports
        run: melos run coverage:combine
        shell: bash
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          dry_run: true
          fail_ci_if_error: true
          files: ./coverage/combined.info
      - name: Dry publish packages
        run: melos publish --dry-run
        shell: bash
